query ListaPersonalExistente {
  personalExistente {
    id
    created_at
    Verificador
    User_id
    RUN
    Nombres
    Apellidos
    Fecha_modificacion
  }
}


mutation NuevoPersonalExistente($EntradaPersonas: EntradaPersona = {Alias: "", Nombres: "", Apellidos: "", Verificador: "", RUN: 10}) {
  NuevoPersonal(EntradaPersonas: $EntradaPersonas) {
    Alias
    Apellidos
    Fecha_modificacion
    Nombres
    RUN
    User_id
    Verificador
  }
}

